service:
  type: ClusterIP
  port: 4141

ingress:
  enabled: false # Мы используем отдельный ресурс Ingress в Terraform
  annotations: {}
  hosts: []
  tls: []

atlantis:
  # GitHub конфигурация
  github:
    user: ${github_user}
    token: ${github_token}
    secret: ${webhook_secret}
    webhookSecret: ${webhook_secret}
  
  # Конфигурация репозиториев
  repoConfig: |
    repos:
      - id: ${github_repo}
        apply_requirements: [approved, mergeable]
        allowed_overrides: [apply_requirements]
        allow_custom_workflows: true
  
  # Безопасность
  security:
    adminPassword: "" # Отключить встроенную аутентификацию
  
  # Ресурсы
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  # Хранилище данных
  persistence:
    enabled: true
    storageClass: "standard"
    accessMode: ReadWriteOnce
    size: 1Gi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: "monitoring"